import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Layout from '@components/Containers/Layout';
import { Button } from '@windmill/react-ui'
import { useState,useEffect,useRef } from 'react';
import { useRouter } from 'next/router';
import { get_REAL_TIME_DB_BASE } from '@utils/constants/db_constants';
import { CrossIcon, TrashIcon,FarmerIcon,WomenDayIcon } from '@icons'
import Link from 'next/link';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

const linkToApk="https://wlz.netlify.app/share/app-release.apk";
const linkToBundle="https://wlz.netlify.app/share/app-release.aab";

// more

export default function Apk() {
  const router = useRouter();
  const DB_BASE_PATH=get_REAL_TIME_DB_BASE(router.pathname);

  
/** Show Toast Notification */
const showToast=(msg:string)=>{
  toast(msg, {
      position: "top-right",
      autoClose: 1000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "light",
      });  
}

  return (
    <Layout>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className="">
      
      {/* Container */}
      <div className="mx-5 mt-3">

        {/* List of farmers */ }
        {true && (
          <div className=''>
              <div className='font-bold'>Women And Land in Zimbabwe Mobile App (WLZ)</div>

              <div className='mt-8'>WLZ APK</div>

              <div className='mt-8'>
                <div
                  onClick={()=>{navigator.clipboard.writeText(linkToApk);showToast("Copied");}} 
                  className='mt-5 inline-flex items-center justify-center space-x-3 border border-slate-300 p-3 rounded-md'>
                  <Link href={linkToApk}>
                  <div className='text-green-500'>
                    <span className='hover:underline'>{linkToApk}</span>
                  </div>
                  </Link>
                  <span className='bg-cyan-300 p-2 rounded-md px-5 hover:cursor-pointer'>Copy</span>
                </div>
              </div>

              <div className='mt-8 mb-2 text-red-600'>WLZ Bundle</div>
              <div className='mt-1'>
                <div
                  onClick={()=>{navigator.clipboard.writeText(linkToBundle);showToast("Copied");}} 
                  className='mt-5 inline-flex items-center justify-center space-x-3 border border-slate-300 p-3 rounded-md'>
                  <Link href={linkToBundle}>
                  <div className='text-green-500'>
                    <span className='hover:underline'>{linkToBundle}</span>
                  </div>
                  </Link>
                  <span className='bg-cyan-300 p-2 rounded-md px-5 hover:cursor-pointer'>Copy</span>
                </div>
              </div>
    
          </div>
        )}
      </div>
      {/* End of Container */}

    </main>

    
    <ToastContainer
        position="top-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="light"
        />
        {/* Same as */}
      <ToastContainer />

    </Layout>
  )
}



