import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Layout from '@components/Containers/Layout';
import { Button } from '@windmill/react-ui'
import { useState,useEffect,useRef } from 'react';
import { useRouter } from 'next/router';
import { get_REAL_TIME_DB_BASE } from '@utils/constants/db_constants';
import { CrossIcon, TrashIcon,FarmerIcon,WomenDayIcon } from '@icons'
import {initFirebase} from "@lib/firebase_db/firebase_init";
import { getDatabase, ref,onValue,set,push} from "firebase/database";
import { child, get, query, orderByChild} from "firebase/database";
import { FARMERMODEL } from '@models/db_model';
import { REALTIME_DB_FARMERS } from '@utils/constants/db_constants';
import AdminDisplayer  from '@components/Dashboard/AdminDisplayer';
import { useAuth } from '@context/auth';
import FarmersDisplayer from '@components/Dashboard/FarmersDisplayer';

const inter = Inter({ subsets: ['latin'] })

export default function Farmers() {
  const router = useRouter();
  const {user,dbuser,userLoading} = useAuth();
  const [ effectCalmer,setEffectCalmer]=useState(null);
  const [ farmersList, setFarmersList] = useState<FARMERMODEL[]>([]);
  const initialFarmersList = useRef<FARMERMODEL[]>([]);

  useEffect(() => {
    // listening for changes in product cart
    // console.log(user);
     (async () => {
         if(true){
             initFirebase();
             const db = getDatabase();

             const orderedRef = query(ref(db,REALTIME_DB_FARMERS), orderByChild('dateCreated'));
             //const cartProdRef = ref(db,DB_BASE_PATH);

             onValue(orderedRef, (snapshot) => {
               //console.log(data);
               //const data = snapshot.val();
               //console.log(data);
               let tempList:FARMERMODEL[]=[];
               snapshot.forEach((child)=>{
                let kidValue=child.val();
                console.log(kidValue);
                tempList.push(kidValue);
               })

               tempList=tempList.reverse();

               if (JSON.stringify(tempList) !== JSON.stringify(initialFarmersList.current)) {
                setFarmersList(tempList);
                initialFarmersList.current = tempList;
               }
               //setWeatherUpdatesList(tempList);
             });
         }
     })();

},[effectCalmer]);

  return (
    <Layout>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className="">
      
      {/* Container */}
      <div className="mx-5 mt-3">

        {/* List of farmers */ }
        {farmersList.length>0 && (
          <div className=''>
          <div className='mb-5 text-xl font-bold dark:text-white'>List of Farmers</div>
          <FarmersDisplayer farmersList={farmersList} dbuser={dbuser}/>
        </div>
        )}

        {/*if List of farmers if empty */}
        {farmersList.length===0 && (
          <div className=''>
            <div className='h-[500px] flex items-center justify-center'>
              <div className='mt-10 flex flex-col items-center justify-center'>
                <div className='font-medium'>
                  No farmers registered yet
                </div>
                <div>
                  <FarmerIcon className="h-[200px] w-[300px]"/>
                </div>
              </div>
            </div>
          </div>
        )}

      </div>
      {/* End of Container */}

    </main>

    </Layout>
  )
}



